= Afiq Lattif - Project Portfolio
:site-section: AboutUs
:toc:
:toc-title:
:toc-placement: preamble
:toclevels: 4
:sectnums:
:imagesDir: ../images
:stylesDir: ../stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-W16-2/main


 PROJECT: SocialCare

---

==  Overview

This portfolio records my contributions to the SocialCare project, under the CS2103T Software Engineering module offered by the School of Computing in NUS.

SocialCare is a volunteer management system that allows Social Welfare Organisations to better manage their volunteers & events, and gain further statistical insights from the data.

The user interacts with it using a Command Line Interface (CLI), and it has a Graphical User Interface (GUI) created with JavaFX.

==   Summary of contributions

My contributions to the project mainly focuses on volunteer management.

* *Major enhancement*: Added *the ability to undo/redo previous commands*
** What it does: Allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: Improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: Affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: Added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.21` (1 release) on GitHub
** Enhancements to existing features:
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** Reviewed PRs (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]

==  Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=command-volunteer-add]

include::../UserGuide.adoc[tag=command-volunteer-list]

include::../UserGuide.adoc[tag=command-volunteer-edit]

include::../UserGuide.adoc[tag=command-volunteer-delete]

==  Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

