= Ngoh Wen Jun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: SocialCare

---

== Overview

This Project Portfolio details my contribution to the SocialCare application. SocialCare is a volunteer management system that allows Social Welfare Organisations to better manage data on their volunteers & events through a Command Line Interface (CLI) using a GUI created with JavaFX. It is written in Java and has about 10kLoC.

The application has a basic Create, Read, Update, Delete (CRUD) function for information about volunteers & events, where the user can switch context at managing either from the volunteer's perspective (CRUD on events participated by a volunteer) or from an event manager's perspective (CRUD on volunteer participation for an event). There is also a feature to print certificates of participation for volunteers on the events they have contributed to, and to import/export the dataset as CSV files.

The project was a software engineering requirement for my project team. We were constrained to morph or enhance a given application AddressBook - Level 4 (link: https://github.com/nus-cs2103-AY1819S1/addressbook-level4). It is used to showcase our ability to work together as a software development team as well as our individual capabilities.

I have been tasked with implementing a feature for dataset movements in and out of the app; referred as *import* & *export* commands in our features.

== Summary of contributions

* *Major enhancement*: added *a command for importing/exporting CSV files* & *a command for exporting infomation as XML files*
** What it does: allows the user to import existing CSV data infomation that is available in current organisation workflows, as well as export them. Infomation can also be exported as XML for reading.
** Justification: This feature allows the transition for current organisation workflow to and fro with our application.

* *Code contributed*: [https://github.com/Scrubbius/main/blob/master/src/main/java/seedu/address/logic/commands/ExportEventXMLCommand.java] [https://github.com/Scrubbius/main/blob/master/src/main/java/seedu/address/logic/commands/ExportVolunteerXMLCommand.java] _{give links to collated code files}_

* *Other contributions*:

** Project management:

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

Here are examples of documentation to show a user how to use the commands I have implemented.

include::../UserGuide.adoc[tag=exportvolunteerxml]

(Copy paste from the UG here)

include::../UserGuide.adoc[tag=exporteventxml]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=XMLstructure]

Here is an example documentation of showing a developer the structure of the XML file output.

(Copy paste from the DG here)

