= Ngoh Wen Jun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: SocialCare

---

== Overview

This portfolio page documents my involvement in SocialCare, a project done as part of the CS2103T Software Engingeering module in NUS.

SocialCare is a Command Line Interace (CLI) app targeted at streamlining mundane administrative tasks social welfare organisations have for managing volunteers and events.

My main role as a Developer for this project was to implement data import/export features so as to help users ease into the app from their existing workflows.

== Summary of contributions

* *Major enhancement*: Added commands to export the entire database of volunteers, and for a specific event as Comma-Separated-Values (CSV) file.
** What it does: Entire database of volunteers can be taken out for reference or editting on other interaces such as excel spreadsheet.
** Justification: Eases the transition of workflow to and fro between SocialCare and commonly used excel spreadsheets to maintain information.
** Highlights: This enhancement required an in-depth knowledge of how CSV files keep information about their tuples to avoid having the data mess up given the entries.


* *Minor enhancement*: Added a skeleton for importing CSV files of the same format as export, and a skeleton for exporting the data in eXtensible Markup Language (XML) format.

* *Code contributed*: https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard/#=undeﬁned&search=Scrubbius


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=exportvolunteercsv]

include::../UserGuide.adoc[tag=exporteventcsv]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

None.


